### PR TITLE
Arithmetic (incremental) backoff in task spin/wait.

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Comment by chriselrod** [comment]
@ranocha I'm curious what the "real world" performance impact is of this PR.

I think Trixi's benchmarks are probably the best example; all I have at the moment are microbenchmarks where this PR shouldn't be showing up (and differences I see seem within noise).
Mind running them (or at least a few) and seeing if it has any impact?

The PR implements a "backing off" in the spin locks, where for each failure, they pause an additional time, up until their pauses start taking a couple microseconds on >= Skylake systems.
This is a compromise between no backing off (original behavior) and the exponential back off recommended by Intel's optimization manual.

**Comment by ranocha** [comment]
Sure, I will run some benchmarks :+1:

**Comment by ranocha** [comment]
I ran the following benchmarks with Julia v1.6.1 and our current development version of Trixi.jl on a AMD Ryzen Threadripper 3990X.

Check out current `master` of ThreadingUtilities.
```julia
julia> using Pkg; Pkg.add("OrdinaryDiffEq"); Pkg.develop("Trixi")

julia> using Pkg; Pkg.activate(temp=true); Pkg.add(["OrdinaryDiffEq", "PkgBenchmark"]); Pkg.develop(["Trixi", "ThreadingUtilities"])

julia> using PkgBenchmark, Trixi

julia> begin
           # ThreadingUtilities master, commit 7517e6086528106c68828468abc36f5c264fce97
           result_master_2threads = benchmarkpkg(Trixi,
               BenchmarkConfig(juliacmd=`$(Base.julia_cmd()) --check-bounds=no --threads=2`))
           writeresults("result_master_2threads.dat", result_master_2threads)

           result_master_16threads = benchmarkpkg(Trixi,
               BenchmarkConfig(juliacmd=`$(Base.julia_cmd()) --check-bounds=no --threads=16`))
           writeresults("result_master_16threads.dat", result_master_16threads)
       end
[...]
```
Exit Julia, check out branch `arithmeticbackoff` of ThreadingUtilities, restart Julia.
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.add(["OrdinaryDiffEq", "PkgBenchmark"]); Pkg.develop(["Trixi", "ThreadingUtilities"])

julia> using PkgBenchmark, Trixi

julia> begin
           # ThreadingUtilities arithmeticbackoff, commit 08ae1cff5964304b913ecbe4eda799931286829d
           result_pr_2threads = benchmarkpkg(Trixi,
               BenchmarkConfig(juliacmd=`$(Base.julia_cmd()) --check-bounds=no --threads=2`))
           writeresults("result_pr_2threads.dat", result_pr_2threads)

           result_pr_16threads = benchmarkpkg(Trixi,
               BenchmarkConfig(juliacmd=`$(Base.julia_cmd()) --check-bounds=no --threads=16`))
           writeresults("result_pr_16threads.dat", result_pr_16threads)
       end
[...]

julia> begin
           result_master_2threads = readresults("result_master_2threads.dat")
           result_pr_2threads     = readresults("result_pr_2threads.dat")
           # order: target, baseline
           results = judge(result_pr_2threads, result_master_2threads)
           export_markdown("results_2threads.md", results)

           result_master_16threads = readresults("result_master_16threads.dat")
           result_pr_16threads     = readresults("result_pr_16threads.dat")
           # order: target, baseline
           results = judge(result_pr_16threads, result_master_16threads)
           export_markdown("results_16threads.md", results)
       end
```

<details>
<summary>

Results with 2 threads
</summary>

## Results
A ratio greater than `1.0` denotes a possible regression (marked with :x:), while a ratio less
than `1.0` denotes a possible improvement (marked with :white_check_mark:). Only significant results - results
that indicate possible regressions or improvements - are shown below (thus, an empty table means that all
benchmark results remained invariant between builds).

| ID                                                                                | time ratio                   | memory ratio  |
|-----------------------------------------------------------------------------------|------------------------------|---------------|
| `["benchmark/elixir_2d_euler_vortex_p4est.jl", "p3_rhs!"]`                        |                1.06 (5%) :x: |    1.00 (1%)  |
| `["structured_3d_dgsem/elixir_advection_nonperiodic.jl", "p3_rhs!"]`              |                1.11 (5%) :x: | 1.02 (1%) :x: |
| `["structured_3d_dgsem/elixir_advection_nonperiodic.jl", "p7_rhs!"]`              |                1.06 (5%) :x: | 1.01 (1%) :x: |
| `["structured_3d_dgsem/elixir_euler_source_terms_nonperiodic.jl", "p3_rhs!"]`     |                   1.01 (5%)  | 1.01 (1%) :x: |
| `["structured_3d_dgsem/elixir_euler_source_terms_nonperiodic.jl", "p7_rhs!"]`     |                1.25 (5%) :x: | 1.01 (1%) :x: |
| `["structured_3d_dgsem/elixir_mhd_ec.jl", "p7_analysis"]`                         |                1.09 (5%) :x: |    1.01 (1%)  |
| `["tree_2d_dgsem/elixir_euler_vortex_mortar.jl", "p7_rhs!"]`                      |                1.05 (5%) :x: |    1.00 (1%)  |
| `["tree_2d_dgsem/elixir_euler_vortex_mortar_shockcapturing.jl", "p3_rhs!"]`       | 0.85 (5%) :white_check_mark: |    1.00 (1%)  |
| `["tree_3d_dgsem/elixir_euler_shockcapturing.jl", "p7_rhs!"]`                     |                   1.01 (5%)  | 1.01 (1%) :x: |
| `["tree_3d_dgsem/elixir_mhd_ec.jl", "p7_rhs!"]`                                   |                   0.97 (5%)  | 1.01 (1%) :x: |
| `["unstructured_2d_dgsem/elixir_euler_wall_bc.jl", "p3_analysis"]`                | 0.94 (5%) :white_check_mark: |    1.00 (1%)  |

## Benchmark Group List
Here's a list of all the benchmark groups executed by this job:

- `["benchmark/elixir_2d_euler_vortex_p4est.jl"]`
- `["benchmark/elixir_2d_euler_vortex_structured.jl"]`
- `["benchmark/elixir_2d_euler_vortex_tree.jl"]`
- `["benchmark/elixir_2d_euler_vortex_unstructured.jl"]`
- `["latency"]`
- `["p4est_2d_dgsem/elixir_advection_extended.jl"]`
- `["p4est_3d_dgsem/elixir_advection_basic.jl"]`
- `["structured_2d_dgsem/elixir_advection_extended.jl"]`
- `["structured_2d_dgsem/elixir_advection_nonperiodic.jl"]`
- `["structured_2d_dgsem/elixir_euler_ec.jl"]`
- `["structured_2d_dgsem/elixir_euler_source_terms_nonperiodic.jl"]`
- `["structured_2d_dgsem/elixir_mhd_ec.jl"]`
- `["structured_3d_dgsem/elixir_advection_nonperiodic.jl"]`
- `["structured_3d_dgsem/elixir_euler_ec.jl"]`
- `["structured_3d_dgsem/elixir_euler_source_terms_nonperiodic.jl"]`
- `["structured_3d_dgsem/elixir_mhd_ec.jl"]`
- `["tree_2d_dgsem/elixir_advection_amr_nonperiodic.jl"]`
- `["tree_2d_dgsem/elixir_advection_extended.jl"]`
- `["tree_2d_dgsem/elixir_euler_ec.jl"]`
- `["tree_2d_dgsem/elixir_euler_vortex_mortar.jl"]`
- `["tree_2d_dgsem/elixir_euler_vortex_mortar_shockcapturing.jl"]`
- `["tree_2d_dgsem/elixir_mhd_ec.jl"]`
- `["tree_3d_dgsem/elixir_advection_extended.jl"]`
- `["tree_3d_dgsem/elixir_euler_ec.jl"]`
- `["tree_3d_dgsem/elixir_euler_mortar.jl"]`
- `["tree_3d_dgsem/elixir_euler_shockcapturing.jl"]`
- `["tree_3d_dgsem/elixir_mhd_ec.jl"]`
- `["unstructured_2d_dgsem/elixir_euler_wall_bc.jl"]`

## Julia versioninfo

### Target
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
      Ubuntu 20.04.2 LTS
  uname: Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64
  CPU: AMD Ryzen Threadripper 3990X 64-Core Processor:
                  speed         user         nice          sys         idle          irq
       #1-128  2860 MHz  1090183386 s       5832 s     881686 s  2996292152 s          0 s

  Memory: 251.6334342956543 GB (3754.9375 MB free)
  Uptime: 3.194432e6 sec
  Load Avg:  1.25  1.24  1.29
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```

### Baseline
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
      Ubuntu 20.04.2 LTS
  uname: Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64
  CPU: AMD Ryzen Threadripper 3990X 64-Core Processor:
                  speed         user         nice          sys         idle          irq
       #1-128  2198 MHz  1090130263 s       5832 s     881119 s  2992235492 s          0 s

  Memory: 251.6334342956543 GB (3842.1015625 MB free)
  Uptime: 3.19122e6 sec
  Load Avg:  1.37  1.26  1.14
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```
</details>


<details>
<summary>

Results with 16 threads
</summary>

## Results
A ratio greater than `1.0` denotes a possible regression (marked with :x:), while a ratio less
than `1.0` denotes a possible improvement (marked with :white_check_mark:). Only significant results - results
that indicate possible regressions or improvements - are shown below (thus, an empty table means that all
benchmark results remained invariant between builds).

| ID                                                                                | time ratio    | memory ratio  |
|-----------------------------------------------------------------------------------|---------------|---------------|
| `["benchmark/elixir_2d_euler_vortex_p4est.jl", "p7_rhs!"]`                        | 1.12 (5%) :x: | 1.05 (1%) :x: |
| `["benchmark/elixir_2d_euler_vortex_structured.jl", "p7_rhs!"]`                   | 1.14 (5%) :x: | 1.13 (1%) :x: |
| `["benchmark/elixir_2d_euler_vortex_tree.jl", "p7_rhs!"]`                         | 1.15 (5%) :x: | 1.09 (1%) :x: |
| `["benchmark/elixir_2d_euler_vortex_unstructured.jl", "p7_rhs!"]`                 | 1.13 (5%) :x: | 1.08 (1%) :x: |
| `["p4est_2d_dgsem/elixir_advection_extended.jl", "p7_rhs!"]`                      |    1.05 (5%)  | 1.15 (1%) :x: |
| `["p4est_3d_dgsem/elixir_advection_basic.jl", "p3_rhs!"]`                         | 1.14 (5%) :x: | 1.12 (1%) :x: |
| `["p4est_3d_dgsem/elixir_advection_basic.jl", "p7_rhs!"]`                         | 1.37 (5%) :x: | 1.13 (1%) :x: |
| `["structured_2d_dgsem/elixir_advection_extended.jl", "p7_rhs!"]`                 |    1.05 (5%)  | 1.07 (1%) :x: |
| `["structured_2d_dgsem/elixir_euler_ec.jl", "p7_rhs!"]`                           | 1.10 (5%) :x: | 1.12 (1%) :x: |
| `["structured_2d_dgsem/elixir_euler_source_terms_nonperiodic.jl", "p7_rhs!"]`     | 1.13 (5%) :x: | 1.01 (1%) :x: |
| `["structured_3d_dgsem/elixir_advection_nonperiodic.jl", "p3_rhs!"]`              | 1.12 (5%) :x: | 1.42 (1%) :x: |
| `["structured_3d_dgsem/elixir_advection_nonperiodic.jl", "p7_rhs!"]`              | 1.24 (5%) :x: | 1.52 (1%) :x: |
| `["structured_3d_dgsem/elixir_euler_ec.jl", "p7_rhs!"]`                           | 1.37 (5%) :x: | 1.23 (1%) :x: |
| `["structured_3d_dgsem/elixir_euler_source_terms_nonperiodic.jl", "p3_rhs!"]`     | 1.23 (5%) :x: | 1.21 (1%) :x: |
| `["structured_3d_dgsem/elixir_euler_source_terms_nonperiodic.jl", "p7_rhs!"]`     | 1.13 (5%) :x: | 1.23 (1%) :x: |
| `["structured_3d_dgsem/elixir_mhd_ec.jl", "p7_rhs!"]`                             | 1.37 (5%) :x: | 1.23 (1%) :x: |
| `["tree_2d_dgsem/elixir_euler_ec.jl", "p3_rhs!"]`                                 | 1.13 (5%) :x: | 1.08 (1%) :x: |
| `["tree_2d_dgsem/elixir_euler_ec.jl", "p7_rhs!"]`                                 | 1.52 (5%) :x: | 1.09 (1%) :x: |
| `["tree_2d_dgsem/elixir_euler_vortex_mortar.jl", "p7_rhs!"]`                      | 1.18 (5%) :x: | 1.13 (1%) :x: |
| `["tree_2d_dgsem/elixir_euler_vortex_mortar_shockcapturing.jl", "p3_rhs!"]`       | 1.12 (5%) :x: |    1.00 (1%)  |
| `["tree_2d_dgsem/elixir_euler_vortex_mortar_shockcapturing.jl", "p7_rhs!"]`       | 1.30 (5%) :x: | 1.08 (1%) :x: |
| `["tree_2d_dgsem/elixir_mhd_ec.jl", "p7_rhs!"]`                                   | 1.36 (5%) :x: | 1.16 (1%) :x: |
| `["tree_3d_dgsem/elixir_advection_extended.jl", "p7_rhs!"]`                       | 1.26 (5%) :x: | 1.17 (1%) :x: |
| `["tree_3d_dgsem/elixir_euler_ec.jl", "p3_rhs!"]`                                 | 1.32 (5%) :x: | 1.20 (1%) :x: |
| `["tree_3d_dgsem/elixir_euler_ec.jl", "p7_rhs!"]`                                 | 1.36 (5%) :x: | 1.12 (1%) :x: |
| `["tree_3d_dgsem/elixir_euler_mortar.jl", "p7_rhs!"]`                             | 1.21 (5%) :x: | 1.06 (1%) :x: |
| `["tree_3d_dgsem/elixir_euler_shockcapturing.jl", "p3_rhs!"]`                     | 1.29 (5%) :x: | 1.13 (1%) :x: |
| `["tree_3d_dgsem/elixir_euler_shockcapturing.jl", "p7_rhs!"]`                     | 1.36 (5%) :x: | 1.11 (1%) :x: |
| `["tree_3d_dgsem/elixir_mhd_ec.jl", "p7_rhs!"]`                                   | 1.36 (5%) :x: | 1.19 (1%) :x: |
| `["unstructured_2d_dgsem/elixir_euler_wall_bc.jl", "p3_analysis"]`                | 1.07 (5%) :x: |    1.00 (1%)  |

## Benchmark Group List
Here's a list of all the benchmark groups executed by this job:

- `["benchmark/elixir_2d_euler_vortex_p4est.jl"]`
- `["benchmark/elixir_2d_euler_vortex_structured.jl"]`
- `["benchmark/elixir_2d_euler_vortex_tree.jl"]`
- `["benchmark/elixir_2d_euler_vortex_unstructured.jl"]`
- `["latency"]`
- `["p4est_2d_dgsem/elixir_advection_extended.jl"]`
- `["p4est_3d_dgsem/elixir_advection_basic.jl"]`
- `["structured_2d_dgsem/elixir_advection_extended.jl"]`
- `["structured_2d_dgsem/elixir_advection_nonperiodic.jl"]`
- `["structured_2d_dgsem/elixir_euler_ec.jl"]`
- `["structured_2d_dgsem/elixir_euler_source_terms_nonperiodic.jl"]`
- `["structured_2d_dgsem/elixir_mhd_ec.jl"]`
- `["structured_3d_dgsem/elixir_advection_nonperiodic.jl"]`
- `["structured_3d_dgsem/elixir_euler_ec.jl"]`
- `["structured_3d_dgsem/elixir_euler_source_terms_nonperiodic.jl"]`
- `["structured_3d_dgsem/elixir_mhd_ec.jl"]`
- `["tree_2d_dgsem/elixir_advection_amr_nonperiodic.jl"]`
- `["tree_2d_dgsem/elixir_advection_extended.jl"]`
- `["tree_2d_dgsem/elixir_euler_ec.jl"]`
- `["tree_2d_dgsem/elixir_euler_vortex_mortar.jl"]`
- `["tree_2d_dgsem/elixir_euler_vortex_mortar_shockcapturing.jl"]`
- `["tree_2d_dgsem/elixir_mhd_ec.jl"]`
- `["tree_3d_dgsem/elixir_advection_extended.jl"]`
- `["tree_3d_dgsem/elixir_euler_ec.jl"]`
- `["tree_3d_dgsem/elixir_euler_mortar.jl"]`
- `["tree_3d_dgsem/elixir_euler_shockcapturing.jl"]`
- `["tree_3d_dgsem/elixir_mhd_ec.jl"]`
- `["unstructured_2d_dgsem/elixir_euler_wall_bc.jl"]`

## Julia versioninfo

### Target
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
      Ubuntu 20.04.2 LTS
  uname: Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64
  CPU: AMD Ryzen Threadripper 3990X 64-Core Processor:
                  speed         user         nice          sys         idle          irq
       #1-128  2198 MHz  1090210977 s       5832 s     881975 s  2997939405 s          0 s

  Memory: 251.6334342956543 GB (3858.0390625 MB free)
  Uptime: 3.195741e6 sec
  Load Avg:  4.06  3.12  2.16
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```

### Baseline
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
      Ubuntu 20.04.2 LTS
  uname: Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64
  CPU: AMD Ryzen Threadripper 3990X 64-Core Processor:
                  speed         user         nice          sys         idle          irq
       #1-128  2199 MHz  1090166323 s       5832 s     881330 s  2993869497 s          0 s

  Memory: 251.6334342956543 GB (3817.6484375 MB free)
  Uptime: 3.192525e6 sec
  Load Avg:  5.33  4.08  2.78
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```

</details>

**Comment by chriselrod** [comment]
Great, thanks. So it looks like this PR regresses performance.

**Pull request closed without merging**
